name: Daily Commit (No Bash)

on:
  schedule:
    # Runs once per day at 08:03 UTC (pick any exact time you like)
    - cron: "3 8 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  commit-daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Step name includes your email, per the instructions.
      - name: Update heartbeat (22f3002558@ds.study.iitm.ac.in)
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const ts = new Date().toISOString();
            fs.writeFileSync('.daily_heartbeat.txt', `Last run at ${ts}\n`);

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily heartbeat"
          file_pattern: .daily_heartbeat.txt
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
